language: node_js
node_js:
- '0.12'

before_install:
- npm install -g gulpjs/gulp-cli#4.0

after_success:
- npm start
- bash ./deploy.sh

env:
  global:
  - GH_REF: github.com/hyzhak/hyzhak.github.io.git
  - secure: cx162IsI/A7kPajB3B9oi3nKct2MmfWAzki6KeFSHgO+udJajDkv34Tb+4Mxt7prwEuT7wJnwMhZcNj0zykJsvh2gXHLSHE1rABWRw5w3myCaOnt9l+WfVsjgBlMXgHa6mN34zQttZHop6k+hOD4wAPldOENb24/kWnsFDEZhxD8jpoJ9B7edaDUJcAqQDTetQZeGaPpXMLlnOC5Vr4PH0oYsI/CJ/scMSoL98XWsam4oWefCpQauyLG5HnVZyU0P4rCWCbs8oiOgaO4xdk3X+KM4bwdk0Ivzi/V2Rl3o35Y0BeILWKrSrSW51pQ8k4cj6AMJsAqEYhDSO2XvxPKtvd9ZKRDpAUr79S9ldIeedAWeG8mvd0AZmmx7OwHZhNIgZCVRLwH+fx3NtzlF7IpFA30uxC7ohkT9N4wKZBA7bkY2wOXy8qM/pZYfj2Aee0Ts0djyT0T0+ru+XxCydJ9oIbTk1yPIUJkPaLQR7kJJXfdSRV+IC+XOTBLEnIlO2gtw6b7m65VEMIffDoorGPARlGqUmD6RZlY4TCexz/TFj5IxPpjbWEdkgd/+hq81h9hqfoEu6b63EB5/1rdiIAyKB/PSOgTd8Bc6BH9PDLN6lqDi2EGt5Z04BDMVCZtY+eRFM8v06HreWnZNLdshfHWnm0JlSNdVxeCg/IDm2Jl2+o=
