# site globals
site:
  url: http://hyzhak.github.io
  name: Eugene Krevenets
  img: /images/me.jpg
  description: Full stack developer (node.js, python, javascript)
  build: dist
  keywords: game dev, javascript, node.js, python, opensource

email:
  account: ievgenii.krevenets@gmail.com

facebook:
  account: hyzhak.github.io
  appid: 1442302082756159

github:
  account: hyzhak

google:
  analytics: UA-38043860-12
  verification: "-WuDSQXcQ3LYVkL0N9vaxK-5xrxXS4I-nB9t5qreNjU" # Google webmaster verification

linkedin:
  account: eugenekrevenets

twitter:
  account: hyzhak_en
